// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["postgresql://neondb_owner:npg_5OaTLfBqtz6K@ep-red-shape-aln5lci0-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"],
  },
});
